# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

before_install:
    - tlmgr install texlive-latex-extra
    - tlmgr install collection-latexrecommended
    - tlmgr update --all
    
language: R
cache: packages
branches:
  only:
  - master
