# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

before_install:
    - sudo apt-get install texlive texlive-latex3
    - sudo apt install texlive-latex-extra
    - tlmgr install collection-latexrecommended
    - tlmgr update --all
    
language: R
cache: packages
branches:
  only:
  - master
